config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'posts/home'
  root 'posts#home'
  devise_for :users
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
 resources :users, only: [:show ,:index]
 
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

  end

  
  resources :diaries
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user  

    has_many :comments, dependent: :destroy

    has_many :post_tag_relations, dependent: :destroy

    has_many :tags, through: :post_tag_relations, dependent: :destroy

    validates :body, exclusion: { in: ["殺すぞ", "死ね","ブス"] }
    
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_relations, dependent: :destroy

    has_many :posts, through: :post_tag_relations, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,  dependent: :destroy
  validates :name, presence: true
  validates :profile, length:{ maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  has_many :diarys

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id],post_id: params[:post_id])
    comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end


end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!


    def index
        @diarys = Diary.where(user_id: current_user.id).page(params[:calendar]).per(31).order(id: "DESC")
        @vactine = Diary.where(user_id: current_user.id).page(params[:index]).per(3).order(id: "DESC")
      end
    
    def new
        @diary = Diary.new
    end

    def show
        @diary = Diary.find(params[:id])
    end
    
    def create
        # Diary.create(diary_parameter)
        diary = Diary.new(diary_parameter)
        diary.user_id = current_user.id

        if diary.save
          redirect_to diaries_path
        else
          redirect_to action: "new"
        end

    end

    def destroy
        diary = Diary.find(params[:id])
        diary.destroy
        redirect_to diaries_path, notice:"削除しました"
    end

    def edit
        @diary = Diary.find(params[:id])
    end
    
    def update
        @diary = Diary.find(params[:id])
        if @diary.update(diary_parameter)
          redirect_to diaries_path, notice: "編集しました"
        else
          render 'edit'
        end
    end

    private

  def diary_parameter
    params.require(:diary).permit(:title, :content, :start_time)
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
      end
    
    def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def home

    end

    before_action :authenticate_user!, except: [:home]

    def index

        if params[:search] == nil
            @posts= Post.all.page(params[:page]).per(3).order(id: "DESC")
        elsif params[:search] == ''
            @posts= Post.all.page(params[:page]).per(3)
        else
            @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3).order(id: "DESC")
        end
        
        if params[:tag_ids]
            @posts = []
            params[:tag_ids].each do |key, value|
            　if value == "1"
                tag_posts = Tag.find_by(name: key).posts
                @posts = @posts.empty? ? tag_posts : @posts & tag_posts
            　end
            end
        end

    end

    

    def new
        @post = Post.new
    end

    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save
            redirect_to :action =>"index"
        else
            flash[:notice] = "優しい投稿を心がけましょう"
            redirect_to :action => "new"
        end
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end

      

    private
    def post_params
        params.require(:post).permit(:title,:body,:image, tag_ids: [])
    end
    
    

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to posts_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  
  def show
    @user = User.find(params[:id])
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end
    
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  
end

app/views/diaries/edit.html.erb
<%= form_with(model: @diary, local: true) do |form| %>

    <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
    </div>
      
    
      <div class="time">
        <%= form.label :start_time %>
        <%= form.datetime_select :start_time %>
      </div>
  
      <div class="content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    
    
      <div class="submit">
        <%= form.submit %>
      </div>
    
    <% end %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<div class="diary-title">ポジティブ日記</div>
<p class="diary-text">今日あったいいこと、頑張ったこと、できたことをなんでもいいので書いて自分を褒めましょう！</p> 


<br>
<div class="diary-post">
<%= link_to '日記をかく', new_diary_path %>
</div>

<%= month_calendar events: @diarys do |date, diarys| %>
  <%= date.day %>

  <% diarys.each do |diary| %>
    <div>
      <%= link_to diary.title, diary %>
    </div>
    <% end %>
    
    <% if diarys.length > 2 %>
    <%= paginate @diarys, :params_name => 'calendar' %>
    <% end %>

<% end %>

<tbody>
<%= page_entries_info @diarys %>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= page_entries_info @vactine %>

    <% @vactine.each do |d| %>
      <tr>
          <td><%= d.title %></td>
          <td><%= d.start_time.strftime("%Y-%m-%d %H:%M") %></td>

          <td><%= link_to '詳細', d %></td>
          <td><%= link_to '編集', edit_diary_path(d.id) %></td>
          <td><%= link_to '削除',diary_path(d.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @vactine , :param_name => 'index' %>

app/views/diaries/new.html.erb
<%= form_with(model: @diary, local: true) do |form| %>

  <div class="diary-post-title">
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>
    
  
    <div class="time">
      <%= form.label :start_time %>
      <%= form.datetime_select :start_time %>
    </div>

    <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  
    <div class="submit">
      <%= form.submit %>
    </div>
  
  <% end %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @diary.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @diary.content %>
</p>

<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '戻る', diaries_path %>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <div class="field">
      <%= f.label :タイトル %>
      <%= f.text_field :title, :size => 40 %>
      <%= f.label :内容 %>
      <%= f.text_field :body, :size => 140 %>
    </div>
    <div class="field">
      <%= f.label :画像 %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit "編集する" %>
  <% end %>
  <%= link_to "投稿一覧に戻る", posts_path %>

app/views/posts/home.html.erb
    <div class="first-block">
        <div class="top-image">
        </div>
        <div class= "about-1"> 
            <p><b>ここにはあなたを否定する人は人はいません</b><br>
            何かとストレスが溜まりやすい現代なので、悩んでいる人や疲れている人の逃げ場として
            現代の駆け込み寺のようなSNSを作りました
            </p>
            <%= link_to "みんなのお悩みをみる", posts_path %>
        </div>
    </div>

    <div class="second-block">
        <div class= "about-2">
            <p><b>あなたの悩みを吐き出しましょう</b><br>
            一人で抱えている不安や悩みを吐き出してみましょう。
            誰かに話すだけでも少し肩の荷が降りるかもしれません</p>
            <%= link_to "お悩みを相談する", new_post_path %>
        </div>
        <div class="middle-image">
        
        </div>


    </div>
    <div class= "third-block">
        <div class="bottom-image">
        </div>
        <div class= "about-3">
            <p><b>ポジティブな感情も吐き出しましょう</b><br>
            今日のできたこと、嬉しかったこと、褒められたことなど些細なことでもいいので
            書き出して自己肯定感をあげましょう！
            </p>
            <%= link_to "ポジティブ日記を書く", diaries_path %>
        </div>
    </div>

app/views/posts/index.html.erb
<h1 class ="heading">
<p>ここにはあなたを否定したりする人はいません<br>
人に話しづらい悩み事、辛いこと、困っていることを吐き出しましょう</p>
<%= link_to "新規投稿へ", new_post_path %>
</h1>

<div class = "search-container">
  <div> 投稿を検索 </div> 
  <%= form_tag({controller:"posts",action:"index"}, method: :get, class:'search-form' ) do %>
    <%= text_field_tag :search %>
    <%= button_tag :type => "submit", :class =>"search-button" do %>
      <i class="fa fa-search"></i>
    <% end %>  
    <% end %>
  <br>

  <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>
    <%= select_tag :tag_id,
        options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
          {
            prompt: 'タグで絞り込み検索',
            onchange: 'submit(this.form);'
            }
    %>
<% end %>
</div>

<h2 class = "post-index"> 投稿一覧 </div>

<div class="posts-container">
  <a class = "pagenate"><%= paginate @posts %></a>
  <% @posts.each do |p| %>
    <div class="post">
      <a class="post-name"href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
      <p class= "post-title"><%= p.title %></p>
      <p class= "post-body"><%= p.body %></p>
      <% if p.image? %>
      <p class= "post-image"><%= image_tag p.image_url, size: "250x200" if p.image? %></p>
      <% end %>
      <br>
      <p class= "post-tags"><% p.tags.each do |tag| %></p>
      <span class= "tag"><%= tag.name %></span><br>
      <% end %>

      
    <% if user_signed_in? %>
      <% if current_user.already_liked?(p) %>
          <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= p.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
            <i class="far fa-heart"></i><%= p.likes.count %>
          <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= p.likes.count %>
    <% end %>

      <%= p.created_at %>
    <%= link_to "詳細へ", post_path(p.id) %>
    <% if user_signed_in? && current_user.id == p.user_id  %> 
      <%= link_to "編集する", edit_post_path(p.id) %>
      <%= button_to "削除する", post_path(p.id), method: :delete %>
    <% elsif current_user == @user || current_user.admin? %>
      <%= link_to "編集する", edit_post_path(p.id) %>
    <%= button_to "削除する", post_path(p.id), method: :delete %>
    
    <% end %>

    <% if user_signed_in? %>
      <% if current_user != p.user %>
        <% if p.user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(p.user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(p.user.id), method: :post %></p>
        <% end %>
      <% end %>
    <% end %>
    </div>

  <% end %>
  <%= page_entries_info @posts %>
  <%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class= "post-show">投稿詳細</div>
<div class="post">
  <a href="/users/<%= @post.user.id %>"><%= @post.user.name %></a>
  <p class="post-title"><%= @post.title %></p>
  <p class="post-body"><%= @post.body %></p>
  <% if @post.image? %>
  <p class= "post-image"><%= image_tag @post.image_url, size: "250x200" if @post.image? %></p>
  <% end %>
  <p><%= @post.created_at %></p>

  <% @post.tags.each do |tag| %>
    <span class= "tag"><%= tag.name %></span>
  <% end %>

  <% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "編集する", edit_post_path(@post.id) %>
    <%= button_to "削除する", post_path(@post.id), method: :delete %>
  <% end %>

  <% if current_user != @post.user %>
        <% if @post.user.followed_by?(current_user) %>
            <p class="follow"><%=link_to "フォロー済み", user_relationships_path(@post.user.id), method: :delete %></p>
        <% else %>
            <p class="follow"><%=link_to "フォローする", user_relationships_path(@post.user.id), method: :post %></p>
        <% end %>
    <% end %>


  <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>

          <% end %>
      <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= @post.likes.count %>
  <% end %>

  <div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.name unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
      <% if user_signed_in? && current_user.id == c.user_id  %> 
        <%= button_to "削除する", post_comment_path(c.post.id, c.id), method: :delete %>
      <% elsif current_user == @user || current_user.admin? %>
        <%= button_to "削除する", post_comment_path(c.post.id, c.id), method: :delete %>
      <% end %>


  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %><br>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

</div>
<div class= "back">
<%= link_to "投稿一覧に戻る", posts_path %>
</div>